### ISSUE TITLE
Using an empty struct as a param causes panic

### ISSUE THREAD

**Issue by dominicbarnes** [segmentio/glue#15]
If you have a method with an empty/anonymous `struct{}` as the type for params, it'll panic:

```
panic: unexpected type: *types.Struct
```

**Comment by tejasmanohar** [comment]
Ah, the fix should be as simple as https://github.com/segmentio/glue/commit/5390362d7894d4dca382e582c5e04a43014e330a, but it should be possible to avoid this class of problem using a strategy like the one proposed in https://github.com/segmentio/glue/issues/16.
