### ISSUE TITLE
Generate a client interface

### ISSUE THREAD

**Issue by tejasmanohar** [segmentio/glue#9]
We _may_ want this. Some people have asked for it, but after mentioning Go is opportunistically typed and you can make your own interface, some have said they can do without it. So... not sure whether or not we want to add this. It's a simple change to the template file if we do! I'd merge any PR that added it.

I added people who asked about it as assignees for feedback on the idea

**Comment by boggsboggs** [comment]
The generated code currently looks like this:
```
func NewTaskRunnerClient(rpcClient client.Client) *TaskRunner {
	c := new(TaskRunner)
	c.RPC = rpcClient
	return c
}

type TaskRunner struct {
	RPC client.Client
}
```

I asked about generating it like this:
```
func NewTaskRunnerClient(rpcClient client.Client) TaskRunner {
	c := new(taskRunner)
	c.RPC = rpcClient
	return c
}

type TaskRunner interface {
	List(args messages.ListRequest) (*messages.ListResponse, error)
	Replay(args messages.ReplayRequest) (*messages.ReplayResponse, error)
	Run(args messages.RunRequest) (*messages.RunResponse, error)
	RunTime(args messages.RunTimeRequest) (*messages.RunTimeResponse, error)
	Status(args messages.StatusRequest) (*messages.StatusResponse, error)
}

type taskRunner struct {
	RPC client.Client
}
```
with the purpose being to make testing easier.

Here's an open source example from, `go-http/jsonrpc-client`
```
type Client interface {
	Call(method string, args interface{}, res interface{}) error
	CallContext(context.Context, string, interface{}, interface{}) error
}

// NewClient creates a new Client that caches DNS responses for 5 minutes, and
// times out RPC requests after 10 minutes each.
func NewClient(addr string) Client {
	dialer := &nett.Dialer{
		Resolver:  &nett.CacheResolver{TTL: 5 * time.Minute},
		Timeout:   1 * time.Minute,
		KeepAlive: 1 * time.Minute,
	}
	return &client{
		addr: addr,
		http: &http.Client{
			Transport: &http.Transport{
				Dial:                dialer.Dial,
				MaxIdleConnsPerHost: 512,
			},
			Timeout: 10 * time.Minute,
		},
	}
}

type client struct {
	http *http.Client
	addr string
}
```

**Comment by boggsboggs** [comment]
Hmm... actually looks like gohttp is mostly Segment...

Anyway, thoughts from someone more experienced with Go?

**Comment by achille-roussel** [comment]
Returning interfaces for constructor-like functions is not considered good practice. The main reason is types tend to evolve quickly, if you need to add a method to that type and you expose it as an interface you end up breaking all other implementations of that interface. 

Interfaces are powerful constructs for writing generic code, the smaller they are the better... everywhere else, the use of concrete types should be preferred.
